#pragma once
#include <torch/extension.h>

torch::Tensor gemv_forward_cuda_uniform(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    const int bit,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_uniform_outlier(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    const int bit,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_normalize(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _stds,
    torch::Tensor _means,
    torch::Tensor _normal_quantiles_center,
    const int bit,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_normalize_outlier(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _stds,
    torch::Tensor _means,
    torch::Tensor _normal_quantiles_center,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    const int bit,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_uniform_group(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_uniform_group_outlier(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_qk_uniform_group_token(
  torch::Tensor _in_feats,
  torch::Tensor _kernel,
  torch::Tensor _scaling_factors,
  torch::Tensor _zeros,
  const int bit,
  const int group_size,
  const int nh_q,
  const int nh_kv);

torch::Tensor gemv_forward_cuda_qk_group_hq(
    torch::Tensor _in_feats,
    c10::optional<torch::Tensor> _kernel_16,
    c10::optional<torch::Tensor> _kernel_16_idx,
    c10::optional<torch::Tensor> _kernel_8,
    c10::optional<torch::Tensor> _kernel_8_idx,
    c10::optional<torch::Tensor> _scaling_factors_8,
    c10::optional<torch::Tensor> _zeros_8,
    c10::optional<torch::Tensor> _kernel_4,
    c10::optional<torch::Tensor> _kernel_4_idx,
    c10::optional<torch::Tensor> _scaling_factors_4,
    c10::optional<torch::Tensor> _zeros_4,
    c10::optional<torch::Tensor> _kernel_2,
    c10::optional<torch::Tensor> _kernel_2_idx,
    c10::optional<torch::Tensor> _scaling_factors_2,
    c10::optional<torch::Tensor> _zeros_2,
    c10::optional<torch::Tensor> _kernel_1,
    c10::optional<torch::Tensor> _kernel_1_idx,
    c10::optional<torch::Tensor> _std_1,
    c10::optional<torch::Tensor> _means_1,
    torch::Tensor _normal_quantiles_center,
    c10::optional<torch::Tensor> _kernel_new,
    int num_out_channels,
    int num_16,
    int num_8,
    int num_4,
    int num_2,
    int num_1,
    int new_len,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_qk_group_hq_seq(
  torch::Tensor _in_feats,
  c10::optional<torch::Tensor> _kernel_16,
  c10::optional<torch::Tensor> _kernel_8,
  c10::optional<torch::Tensor> _scaling_factors_8,
  c10::optional<torch::Tensor> _zeros_8,
  c10::optional<torch::Tensor> _kernel_4,
  c10::optional<torch::Tensor> _scaling_factors_4,
  c10::optional<torch::Tensor> _zeros_4,
  c10::optional<torch::Tensor> _kernel_2,
  c10::optional<torch::Tensor> _scaling_factors_2,
  c10::optional<torch::Tensor> _zeros_2,
  c10::optional<torch::Tensor> _kernel_1,
  c10::optional<torch::Tensor> _std_1,
  c10::optional<torch::Tensor> _means_1,
  torch::Tensor _normal_quantiles_center,
  c10::optional<torch::Tensor> _kernel_new,
  int num_out_channels,
  int num_16,
  int num_8,
  int num_4,
  int num_2,
  int num_1,
  int new_len,
  const int group_size,
  const int nh_q,
  const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_group_hq(
    torch::Tensor _in_feats,
    c10::optional<torch::Tensor> _kernel_16,
    c10::optional<torch::Tensor> _kernel_16_idx,
    c10::optional<torch::Tensor> _kernel_8,
    c10::optional<torch::Tensor> _kernel_8_idx,
    c10::optional<torch::Tensor> _scaling_factors_8,
    c10::optional<torch::Tensor> _zeros_8,
    c10::optional<torch::Tensor> _kernel_4,
    c10::optional<torch::Tensor> _kernel_4_idx,
    c10::optional<torch::Tensor> _scaling_factors_4,
    c10::optional<torch::Tensor> _zeros_4,
    c10::optional<torch::Tensor> _kernel_2,
    c10::optional<torch::Tensor> _kernel_2_idx,
    c10::optional<torch::Tensor> _scaling_factors_2,
    c10::optional<torch::Tensor> _zeros_2,
    c10::optional<torch::Tensor> _kernel_1,
    c10::optional<torch::Tensor> _kernel_1_idx,
    c10::optional<torch::Tensor> _std_1,
    c10::optional<torch::Tensor> _means_1,
    torch::Tensor _normal_quantiles_center,
    c10::optional<torch::Tensor> _kernel_new,
    int num_out_channels,
    int num_16,
    int num_8,
    int num_4,
    int num_2,
    int num_1,
    int new_len,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_group_hq_seq(
  torch::Tensor _in_feats,
  c10::optional<torch::Tensor> _kernel_16,
  c10::optional<torch::Tensor> _kernel_8,
  c10::optional<torch::Tensor> _scaling_factors_8,
  c10::optional<torch::Tensor> _zeros_8,
  c10::optional<torch::Tensor> _kernel_4,
  c10::optional<torch::Tensor> _scaling_factors_4,
  c10::optional<torch::Tensor> _zeros_4,
  c10::optional<torch::Tensor> _kernel_2,
  c10::optional<torch::Tensor> _scaling_factors_2,
  c10::optional<torch::Tensor> _zeros_2,
  c10::optional<torch::Tensor> _kernel_1,
  c10::optional<torch::Tensor> _std_1,
  c10::optional<torch::Tensor> _means_1,
  torch::Tensor _normal_quantiles_center,
  c10::optional<torch::Tensor> _kernel_new,
  int num_out_channels,
  int num_16,
  int num_8,
  int num_4,
  int num_2,
  int num_1,
  int new_len,
  const int group_size,
  const int nh_q,
  const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_group_outlier_hq(
    torch::Tensor _in_feats,
    c10::optional<torch::Tensor> _kernel_16,
    c10::optional<torch::Tensor> _kernel_16_idx,
    c10::optional<torch::Tensor> _kernel_8,
    c10::optional<torch::Tensor> _kernel_8_idx,
    c10::optional<torch::Tensor> _scaling_factors_8,
    c10::optional<torch::Tensor> _zeros_8,
    c10::optional<torch::Tensor> _kernel_4,
    c10::optional<torch::Tensor> _kernel_4_idx,
    c10::optional<torch::Tensor> _scaling_factors_4,
    c10::optional<torch::Tensor> _zeros_4,
    c10::optional<torch::Tensor> _kernel_2,
    c10::optional<torch::Tensor> _kernel_2_idx,
    c10::optional<torch::Tensor> _scaling_factors_2,
    c10::optional<torch::Tensor> _zeros_2,
    c10::optional<torch::Tensor> _kernel_1,
    c10::optional<torch::Tensor> _kernel_1_idx,
    c10::optional<torch::Tensor> _std_1,
    c10::optional<torch::Tensor> _means_1,
    torch::Tensor _normal_quantiles_center,
    c10::optional<torch::Tensor> _kernel_new,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    int num_out_channels,
    int num_16,
    int num_8,
    int num_4,
    int num_2,
    int num_1,
    int new_len,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_uniform_group(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_uniform_group_outlier(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_normalize_group(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _scaling_factors,
    torch::Tensor _zeros,
    torch::Tensor _normal_quantiles_center,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_normalize_group_outlier(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _stds,
    torch::Tensor _means,
    torch::Tensor _normal_quantiles_center,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_qk_normalize_group_token(
  torch::Tensor _in_feats,
  torch::Tensor _kernel,
  torch::Tensor _stds,
  torch::Tensor _means,
  torch::Tensor _normal_quantiles_center,
  const int bit,
  const int group_size,
  const int nh_q,
  const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_normalize_group(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _stds,
    torch::Tensor _means,
    torch::Tensor _normal_quantiles_center,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);

torch::Tensor gemv_forward_cuda_wv_normalize_group_outlier(
    torch::Tensor _in_feats,
    torch::Tensor _kernel,
    torch::Tensor _stds,
    torch::Tensor _means,
    torch::Tensor _normal_quantiles_center,
    torch::Tensor _outliers,
    torch::Tensor _outliers_idx,
    const int bit,
    const int group_size,
    const int nh_q,
    const int nh_kv);